// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PskOnline.Server.Plugins.RusHydro.DAL;

namespace PskOnline.Server.Plugins.RusHydro.DAL.Migrations
{
    [DbContext(typeof(RusHydroPsaDbContext))]
    [Migration("20181205071615_RH_Add_Shift_Ids")]
    partial class RH_Add_Shift_Ids
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PskOnline.Server.Plugins.RusHydro.DAL.Summary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("BranchOfficeId");

                    b.Property<DateTimeOffset>("CompletionTime");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<Guid>("DepartmentId");

                    b.Property<string>("DepartmentShiftReportId");

                    b.Property<Guid>("EmployeeId");

                    b.Property<Guid>("InspectionId");

                    b.Property<long>("ShiftAbsoluteIndex");

                    b.Property<string>("SummaryDocument");

                    b.Property<Guid>("TenantId");

                    b.Property<DateTimeOffset>("UpdateDate");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("BranchOfficeId");

                    b.HasIndex("CompletionTime");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("InspectionId")
                        .IsUnique();

                    b.HasIndex("ShiftAbsoluteIndex");

                    b.HasIndex("TenantId");

                    b.ToTable("RusHydro_Summary");
                });
#pragma warning restore 612, 618
        }
    }
}
