namespace PskOnline.Server.Plugins.RusHydro.DAL
{
  using System;
  using PskOnline.Server.Plugins.RusHydro.ObjectModel;
  using PskOnline.Server.Shared.ObjectModel;

  public class Report : BaseEntity, ITenantEntity
  {
    /// <summary>
    /// gets or sets a unique identifier if the shift in the department across the system
    /// the ID consists of the string representation of the department ID and the string representation of the ID
    /// DB4B5B90-54A8-4A76-A6F4-3785037483FD_
    /// </summary>
    public string DepartmentShiftId { get; set; }

    public Guid TenantId { get; set; }

    public Guid DepartmentId { get; set; }

    public Guid BranchOfficeId { get; set; }

    public DateTime ShiftDate { get; set; }

    public TimeSpan ShiftStartTime { get; set; }

    /// <summary>
    /// gets or sets the name of the shift as a Roman number
    /// ('I', 'II', 'III') or as a verbal name ('день', 'ночь')
    /// </summary>
    public string ShiftName { get; set; }

    /// <summary>
    /// Gets or sets the absolute number of the shift including 
    /// its calendar date, as generated by <see cref="WorkingShiftAbsoluteIndex"/>)
    /// </summary>
    public long ShiftAbsoluteIndex { get; set; }

    public PsaReportDocument ReportDocument { get; set; }
  }
}
