namespace PskOnline.Server.Plugins.RusHydro.DAL
{
  using System;
  using PskOnline.Server.Plugins.RusHydro.ObjectModel;
  using PskOnline.Server.Shared.ObjectModel;

  /// <summary>
  /// class used to store the SummaryDocument in the database with indexing for faster searching
  /// </summary>
  public class Summary : BaseEntity, ITenantEntity
  {
    public Guid TenantId { get; set; }

    public Guid InspectionId { get; set; }

    public Guid DepartmentId { get; set; }

    public Guid BranchOfficeId { get; set; }

    public Guid EmployeeId { get; set; }

    public DateTimeOffset CompletionTime { get; set; }

    public DateTimeOffset UpdateDate { get; set; }

    public SummaryDocument SummaryDocument { get; set; }

    /// <summary>
    /// Gets or sets the absolute number of the shift including 
    /// its calendar date, as generated by <see cref="WorkingShiftAbsoluteIndex"/>)
    /// </summary>
    public long ShiftAbsoluteIndex { get; set; }

    /// <summary>
    /// Gets or sets the absolute unique identifier for the shift
    /// </summary>
    public string DepartmentShiftReportId { get; set; }
  }
}
