namespace PskOnline.Client.Api.Inspection
{
  using System;

  using Newtonsoft.Json.Linq;

  public class TestPostDto
  {
    public string Id { get; set; }

    public string InspectionId { get; set; }

    public string MethodId { get; set; }

    public string MethodVersion { get; set; }

    public DateTimeOffset StartTime { get; set; }

    public DateTimeOffset FinishTime { get; set; }

    /// <summary>
    /// Raw test data recorded by the method client plugin
    /// (in a Web app, a mobile app or in a desktop app)
    /// </summary>
    public JObject MethodRawDataJson { get; set; }

    /// <summary>
    /// Processed test data generated by the
    /// method data processing plugin (on the server)
    /// </summary>
    public JObject MethodProcessedDataJson { get; set; }

    public string Comment { get; set; }
  }
}

