//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PskOnline.Math.Statistics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PskOnline.Math.Statistics.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В результате вычислений значение дисперсии получилось отрицательным!!!.
        /// </summary>
        internal static string cannot_calc_statistics_because_dispersion_is_negative {
            get {
                return ResourceManager.GetString("cannot_calc_statistics_because_dispersion_is_negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ни один замер не попал в диапазон от {0} до {1}!!!
        ///Проверьте параметры расчета статистики!!!.
        /// </summary>
        internal static string no_measurements_fall_into_the_requested_range {
            get {
                return ResourceManager.GetString("no_measurements_fall_into_the_requested_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последовательность содержит слишком мало реализаций (&lt;{0})!.
        /// </summary>
        internal static string series_contains_too_few_measurements {
            get {
                return ResourceManager.GetString("series_contains_too_few_measurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно построить гистограмму распределения с заданными параметрами!.
        /// </summary>
        internal static string unable_to_build_histogram_with_given_arguments {
            get {
                return ResourceManager.GetString("unable_to_build_histogram_with_given_arguments", resourceCulture);
            }
        }
    }
}
