//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PskOnline.Math.Psa.Hrv {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PskOnline.Math.Psa.Hrv.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частота должна быть больше нуля!.
        /// </summary>
        internal static string data_rate_must_be_greater_than_zero {
            get {
                return ResourceManager.GetString("data_rate_must_be_greater_than_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data must be entered before trying to get the results..
        /// </summary>
        internal static string enter_data_before_trying_to_get_result {
            get {
                return ResourceManager.GetString("enter_data_before_trying_to_get_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частота f1 должна быть больше или равна нулю!.
        /// </summary>
        internal static string f1_must_be_greater_than_or_equal_to_0 {
            get {
                return ResourceManager.GetString("f1_must_be_greater_than_or_equal_to_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частота f1 должна быть меньше чем f2!.
        /// </summary>
        internal static string f1_must_be_less_than_f2 {
            get {
                return ResourceManager.GetString("f1_must_be_less_than_f2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частота f2 должна быть больше или равна нулю!.
        /// </summary>
        internal static string f2_must_be_greater_than_or_equal_to_0 {
            get {
                return ResourceManager.GetString("f2_must_be_greater_than_or_equal_to_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение аргумента &apos;freq&apos; должно быть больше нуля!.
        /// </summary>
        internal static string freq_must_be_greater_than_0 {
            get {
                return ResourceManager.GetString("freq_must_be_greater_than_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обе частоты должны быть больше нуля!.
        /// </summary>
        internal static string freqs_must_be_greater_than_0 {
            get {
                return ResourceManager.GetString("freqs_must_be_greater_than_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимально допустимая относительная ширина пика должна быть в диапазоне (0, 1)!.
        /// </summary>
        internal static string maximum_peak_width_must_be_in_range_from_0_to_1 {
            get {
                return ResourceManager.GetString("maximum_peak_width_must_be_in_range_from_0_to_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимально допустимый пульс должен быть больше нуля!.
        /// </summary>
        internal static string maximum_pulse_rate_must_be_greater_than_zero {
            get {
                return ResourceManager.GetString("maximum_pulse_rate_must_be_greater_than_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимально допустимый пульс должен быть больше нуля!.
        /// </summary>
        internal static string minimum_pulse_rate_must_be_greater_than_zero {
            get {
                return ResourceManager.GetString("minimum_pulse_rate_must_be_greater_than_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Желаемое количество отсчетов спектра должно быть степенью двойки!.
        /// </summary>
        internal static string number_of_specturm_bins_must_be_power_of_2 {
            get {
                return ResourceManager.GetString("number_of_specturm_bins_must_be_power_of_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение аргумента &apos;overlap&apos; должно быть в диапазоне [0,1)..
        /// </summary>
        internal static string overlap_must_be_in_range_from_0_to_1 {
            get {
                return ResourceManager.GetString("overlap_must_be_in_range_from_0_to_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В анализируемом сигнале обнаружено менее 3-х пиков. Продолжение обработки невозможно..
        /// </summary>
        internal static string too_few_peaks_found_cannot_continue {
            get {
                return ResourceManager.GetString("too_few_peaks_found_cannot_continue", resourceCulture);
            }
        }
    }
}
