//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PskOnline.Methods.Hrv.Processing.Logic.Personal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class two_dim_conclusions_personal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal two_dim_conclusions_personal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PskOnline.Methods.Hrv.Processing.Logic.Personal.two_dim_conclusions_personal", typeof(two_dim_conclusions_personal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше функциональное состояние, к сожалению, крайне неудовлетворительно. У Вас низкий уровень функциональный возможностей сердечно-сосудистой системы. Высокие уровни физического утомления и напряжения, до максимальных при развитии стресса, частый стабильный пульс. Максимальное напряжение сердечно-сосудистой системы при ее низкой работоспособности и соответственно крайне низком уровне физической работоспособности. Прохождение физиологических процессов при повышенных затратах организма. Заметное ускорение обме [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conclusion_user_1_1 {
            get {
                return ResourceManager.GetString("Conclusion_user_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше функциональное состояние, к сожалению, неудовлетворительное. У Вас низкий уровень функциональный возможностей сердечно-сосудистой системы. Выше среднего уровни физического утомления и напряжения, до заметного — при развитии стресса. Заметное напряжение сердечно-сосудистой системы при ее низкой работоспособности и соответственно крайне низком уровне физической работоспособности. Прохождение физиологических процессов при повышенных затратах организма. Усиление обменных и энергетических процессов. Высокая [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conclusion_user_1_2 {
            get {
                return ResourceManager.GetString("Conclusion_user_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше функциональное состояние к сожалению неудовлетворительное. У Вас низкий уровень функциональный возможностей сердечно-сосудистой системы. Средний уровень напряжения, усиливающийся при развитии стресса, средний уровень физического утомления, крайне низкий уровень физической работоспособности. Заметная неустойчивость к действию спортивных нагрузок. Прохождение физиологических процессов при повышении затрат организма. Усиление обменных и энергетических процессов. Высокая поведенческая активность. Повышение [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conclusion_user_1_3 {
            get {
                return ResourceManager.GetString("Conclusion_user_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше функциональное состояние к сожалению неудовлетворительное. У Вас низкий уровень функциональный возможностей сердечно-сосудистой системы, напряжение и физическое утомление ниже среднего уровня. Появляются заметные признаки истощения при развитии стресса, крайне низкая физическая работоспособность. Заметное замедление и ослабление обменных и энергетических процессов. Прохождение физиологических процессов при повышенных затратах организма. Крайне низкий уровень поведенческой активности, снижение психическ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conclusion_user_1_4 {
            get {
                return ResourceManager.GetString("Conclusion_user_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше функциональное состояние к сожалению неудовлетворительное. У Вас низкий уровень функциональный возможностей сердечно-сосудистой системы, Высокое физическое утомления и напряжение — до максимального истощения при развитии стресса, резкое снижение физической работоспособности. Резкое замедление и ослабление обменных и энергетических процессов с их одновременной активацией. Прохождение физиологических процессов при повышении затрат организма. Крайне низкий уровень поведенческой активности, резкое снижение [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conclusion_user_1_5 {
            get {
                return ResourceManager.GetString("Conclusion_user_1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше функциональное состояние, к сожалению, неудовлетворительное, уровень функциональных возможностей сердечно-сосудистой системы ниже среднего. У Вас заметное нервное напряжение и физическое утомление. Наблюдается явное сопротивление развитию стресса. Учащенный пульс. Энергетические и обменные процессы в Вашем организме ускорены. Вы находитесь в состоянии мобилизации, повышенной психической и поведенческой активности, но физическая работоспособность снижена.
        ///Требуется консультация психотерапевта и терапев [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conclusion_user_2_1 {
            get {
                return ResourceManager.GetString("Conclusion_user_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше функциональное состояние, к сожалению, неудовлетворительное. Уровни напряжения и утомления сердечно-сосудистой системы выше среднего, высокий уровень нервного напряжения. Организм сопротивляется развитию стресса. Энергетические и обменные процессы ускорены. Вы находитесь в состоянии мобилизации, повышенной психической и поведенческой активности. Физическая работоспособность снижена.
        ///Требуется консультация психотерапевта и терапевта, а также всестороннее углубленное клиническое обследование в условиях  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conclusion_user_2_2 {
            get {
                return ResourceManager.GetString("Conclusion_user_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше функциональное состояние к сожалению неудовлетворительное. Хотя напряжение сердечно-сосудистой системы оптимально, утомление отсутствует, а нервное напряжение незначительно, но переносимость физической и спортивной нагрузок снижена. У вас резко снижен уровень физической работоспособности.
        ///Для тренировки организма можно повысить уровень своей физической нагрузки..
        /// </summary>
        internal static string Conclusion_user_2_3 {
            get {
                return ResourceManager.GetString("Conclusion_user_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше функциональное состояние, к сожалению, неудовлетворительное. Уровень функциональных возможностей сердечно-сосудистой системы ниже среднего, наблюдаются явления истощения вследствие развития стресса. Нагрузка на организм существенно выше его функциональных возможностей.
        ///Требуется прекращение деятельности и длительный отдых или отпуск, а также уменьшение уровня своих нагрузок. Если Вы не можете выйти из сложившейся жизненной ситуации, требуется поддержка организма специальными энергетическими, витаминны [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conclusion_user_2_4 {
            get {
                return ResourceManager.GetString("Conclusion_user_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше функциональное состояние к сожалению неудовлетворительное. Напряжение сердечно-сосудистой системы низкое, проявляются заметные явления истощения вследствие развития стресса. Нагрузка на организм резко превышает его функциональные возможности.
        ///Требуется срочное прекращение деятельности и длительный отдых или отпуск. Если Вы не можете выйти из сложившейся жизненной ситуации, требуется поддержка организма специальными энергетическими, витаминными добавками и средствами, содержащими жизненно необходимые м [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conclusion_user_2_5 {
            get {
                return ResourceManager.GetString("Conclusion_user_2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше функциональное состояние в целом удовлетворительное, у Ваc средний уровень функциональных возможностей. Сильное утомление вызвало заметное нервное напряжение и стресс, наблюдается сопротивление развитию стресса. Нагрузка на организм пока соответствует его функциональным возможностям. У Вас оптимальная активность и реакция в условиях меняющейся ситуации. Энергетические и обменные процессы в Вашем организме резко ускорены. Вы находитесь в состоянии мобилизации, повышенной психической и поведенческой акти [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conclusion_user_3_1 {
            get {
                return ResourceManager.GetString("Conclusion_user_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше функциональное состояние в целом удовлетворительное и соответствует среднему уровню функциональных возможностей сердечно-сосудистой системы. У Вас выше среднего уровня утомление, которое вызвало легкие явления нервного напряжения. Нагрузка на организм соответствует его функциональным возможностям. У Вас оптимальная активность и реакция в условиях меняющейся ситуации. Энергетические и обменные процессы в Вашем организме слегка ускорены. Вы находитесь в состоянии мобилизации, повышенной психической и пов [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conclusion_user_3_2 {
            get {
                return ResourceManager.GetString("Conclusion_user_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше функциональное состояние оптимально для сохранения своего здоровья. У Вас полностью отсутствует состояние нервного напряжения и стресс. Идеальная работоспособность сердечно-сосудистой системы.
        ///В таком состоянии специальных дополнительных мероприятий по оздоровлению и профилактике не требуется..
        /// </summary>
        internal static string Conclusion_user_3_3 {
            get {
                return ResourceManager.GetString("Conclusion_user_3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше функциональное состояние в целом удовлетворительное и соответствует среднему уровню функциональных возможностей. Незначительное утомление вызвало легкие явления истощения в функционировании сердечно-сосудистой системы. Нагрузка на организм в целом соответствует его функциональным возможностям, однако Ваша активность слегка снижена. Энергетические и обменные процессы в Вашем организме немного замедлены, наблюдается состояние легкой заторможенности. Способность преодолевать жизненные трудности снижена.
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conclusion_user_3_4 {
            get {
                return ResourceManager.GetString("Conclusion_user_3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше функциональное состояние в целом удовлетворительное и соответствует среднему уровню функциональных возможностей сердечно-сосудистой системы. Однако, в ее работе наблюдается заметные проявления истощения. Формируется состояние, когда нагрузка на организм превышает его функциональные возможности. У Вас существенно снижена активность, энергетические и обменные процессы в организме замедлены. Наблюдается состояние заметной заторможенности. Способность преодолевать жизненные трудности снижена.
        ///Желательно у [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conclusion_user_3_5 {
            get {
                return ResourceManager.GetString("Conclusion_user_3_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваши функциональные возможности выше среднего уровня, однако, заметное утомление вызвало первые проявления нервного напряжения. Начинает появляться тревога, которая может заставить Вас изменить сложившиеся жизненные установки. Организм начинает испытывать излишнюю нагрузку.
        ///Специальных мероприятий по оздоровлению и профилактике не требуется, но крайне желательно провести анализ своего поведения и состояния для их последующей коррекции..
        /// </summary>
        internal static string Conclusion_user_4_1 {
            get {
                return ResourceManager.GetString("Conclusion_user_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваши функциональные возможности выше среднего уровня. Однако появившееся утомление формирует легкое нервное напряжение. Начинает появляться тревога, которая может заставить Вас изменить сложившиеся жизненные установки. Организм начинает испытывать излишнюю нагрузку.
        ///Специальных мероприятий по оздоровлению и профилактике не требуется, но крайне желательно проведение анализа своего поведения и состояния для его последующей коррекции..
        /// </summary>
        internal static string Conclusion_user_4_2 {
            get {
                return ResourceManager.GetString("Conclusion_user_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваши функциональные возможности выше среднего уровня. Утомление отсутствует. У Вас достаточная переносимость физической и спортивной нагрузки.
        ///В таком состоянии специальных дополнительных мероприятий по оздоровлению и профилактике не требуется. Для тренировки организма можно повысить уровень своей физической нагрузки..
        /// </summary>
        internal static string Conclusion_user_4_3 {
            get {
                return ResourceManager.GetString("Conclusion_user_4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваши функциональные возможности выше среднего уровня. Явления утомления отсутствуют. У Вас высокая переносимость физической и спортивной нагрузки.
        ///В таком состоянии специальных дополнительных мероприятий по оздоровлению и профилактике не требуется..
        /// </summary>
        internal static string Conclusion_user_4_4 {
            get {
                return ResourceManager.GetString("Conclusion_user_4_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваши функциональные возможности выше среднего уровня. У Вас невысокая нагрузка на организм и достаточная переносимость физической и спортивной нагрузки.
        ///В таком состоянии специальных дополнительных мероприятий по оздоровлению и профилактике не требуется..
        /// </summary>
        internal static string Conclusion_user_4_5 {
            get {
                return ResourceManager.GetString("Conclusion_user_4_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У Вас высокий уровень функциональных возможностей. Однако заметное утомление вызвало начальную стадию нервного напряжения и стресса. Развивающийся стресс формирует явную тревогу, которая заметно изменяет состояние внутреннего равновесия. Это заставляет Вас менять поведенческую активность. Организм испытывает излишнюю нагрузку.
        ///Специальных мероприятий по оздоровлению и профилактике не требуется, но крайне желательно провести тщательный анализ своего поведения и состояния для его коррекции..
        /// </summary>
        internal static string Conclusion_user_5_1 {
            get {
                return ResourceManager.GetString("Conclusion_user_5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У Вас высокий уровень функциональных возможностей. Однако утомление вызвало нервное напряжение. Начинает появляться тревога, которая может заставить Вас изменить жизненные установки. Организм начинает испытывать излишнюю нагрузку.
        ///Специальных мероприятий по оздоровлению и профилактике не требуется, но крайне желательно провести анализ своего поведения и состояния..
        /// </summary>
        internal static string Conclusion_user_5_2 {
            get {
                return ResourceManager.GetString("Conclusion_user_5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У Вас высокий уровень функциональных возможностей. Признаки утомления отсутствуют. Вы хорошо переносите физическую и спортивную нагрузку.
        ///В таком состоянии специальных дополнительных мероприятий по оздоровлению и профилактике не требуется..
        /// </summary>
        internal static string Conclusion_user_5_3 {
            get {
                return ResourceManager.GetString("Conclusion_user_5_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У Вас высокий уровень функциональных возможностей. Признаки утомления отсутствуют. Отмечается очень высокая переносимость физических и спортивных нагрузок. Однако наблюдаются первые признаки истощения в работе сердечно-сосудистой системы. Возможно состояние перетренировки.
        ///Специальных дополнительных мероприятий по оздоровлению и профилактике не требуется, однако следует увеличить время для отдыха и снизить уровень нагрузок..
        /// </summary>
        internal static string Conclusion_user_5_4 {
            get {
                return ResourceManager.GetString("Conclusion_user_5_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У Вас высокий уровень функциональных возможностей, однако, обнаруживаются признаки заметного истощения. Переносимость физической и спортивной нагрузки снижается, возможно развитие состояния перетренированности.
        ///В таком состоянии следует прекратить все физические нагрузки. Желателен перерыв в работе, отдых в профилактории, отпуск со сменой деятельности. Требуется прием витаминов, специальных пищевых добавок с повышенным содержанием жизненно необходимых минеральных веществ, а также препаратов, улучшающих эне [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conclusion_user_5_5 {
            get {
                return ResourceManager.GetString("Conclusion_user_5_5", resourceCulture);
            }
        }
    }
}
