//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PskOnline.Methods.Svmr.Processing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PskOnline.Methods.Svmr.Processing.resources", typeof(resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реализация теста:.
        /// </summary>
        internal static string Implementation_colon {
            get {
                return ResourceManager.GetString("Implementation_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интервал, с: мин.: {0}, макс.: {1}.
        /// </summary>
        internal static string intervals_min_max_format {
            get {
                return ResourceManager.GetString("intervals_min_max_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аппаратная.
        /// </summary>
        internal static string RealizationType_Hardware {
            get {
                return ResourceManager.GetString("RealizationType_Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программная.
        /// </summary>
        internal static string RealizationType_Software {
            get {
                return ResourceManager.GetString("RealizationType_Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стимулов: тренировочных {0}, зачетных {1}, всего {2}..
        /// </summary>
        internal static string Stimuli_types_list {
            get {
                return ResourceManager.GetString("Stimuli_types_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таймаут, с: {0}.
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исходные данные содержат слишком мало ({0}) нормальных реакций для расчета статистики..
        /// </summary>
        internal static string too_few_valid_reactions_in_results_format {
            get {
                return ResourceManager.GetString("too_few_valid_reactions_in_results_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно расчитать показатели Зимкиной-Лоскутовой..
        /// </summary>
        internal static string zl_not_enough_data {
            get {
                return ResourceManager.GetString("zl_not_enough_data", resourceCulture);
            }
        }
    }
}
