//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PskOnline.Methods.Hrv.Processing.Logic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PskOnline.Methods.Hrv.Processing.Logic.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исходный сигнал.
        /// </summary>
        internal static string AnalyzedSignal {
            get {
                return ResourceManager.GetString("AnalyzedSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заданная длительность теста, с: {0}.
        /// </summary>
        internal static string assigned_test_duration {
            get {
                return ResourceManager.GetString("assigned_test_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры усредненного кардио-цикла.
        /// </summary>
        internal static string AverageCycleParameters {
            get {
                return ResourceManager.GetString("AverageCycleParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спектр кардиоинтервалов.
        /// </summary>
        internal static string CardioIntervalsSpectrum {
            get {
                return ResourceManager.GetString("CardioIntervalsSpectrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Верхняя граница спектра кардио-интервалов.
        /// </summary>
        internal static string CardioIntervalsSpectrum_HiLimit {
            get {
                return ResourceManager.GetString("CardioIntervalsSpectrum_HiLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нижняя граница спектра кардио-интервалов.
        /// </summary>
        internal static string CardioIntervalsSpectrum_LowLimit {
            get {
                return ResourceManager.GetString("CardioIntervalsSpectrum_LowLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заключение.
        /// </summary>
        internal static string Conclusion {
            get {
                return ResourceManager.GetString("Conclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика ВКР (для ряда интервалов в миллисекундах).
        /// </summary>
        internal static string CrvStatistics {
            get {
                return ResourceManager.GetString("CrvStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A0, мВ.
        /// </summary>
        internal static string CycleParams_A0 {
            get {
                return ResourceManager.GetString("CycleParams_A0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1, мВ.
        /// </summary>
        internal static string CycleParams_A1 {
            get {
                return ResourceManager.GetString("CycleParams_A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T, мс.
        /// </summary>
        internal static string CycleParams_T {
            get {
                return ResourceManager.GetString("CycleParams_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T0, мс.
        /// </summary>
        internal static string CycleParams_T0 {
            get {
                return ResourceManager.GetString("CycleParams_T0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T1, мс.
        /// </summary>
        internal static string CycleParams_T1 {
            get {
                return ResourceManager.GetString("CycleParams_T1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HF.
        /// </summary>
        internal static string HF {
            get {
                return ResourceManager.GetString("HF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Триангулярный индекс ВКР.
        /// </summary>
        internal static string HRV_Triangular_Index {
            get {
                return ResourceManager.GetString("HRV_Triangular_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Индекс напряжения (ИН).
        /// </summary>
        internal static string IN {
            get {
                return ResourceManager.GetString("IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание режима обследования.
        /// </summary>
        internal static string InspectionModeDescription {
            get {
                return ResourceManager.GetString("InspectionModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последовательность кардиоинтервалов.
        /// </summary>
        internal static string IntervalsArray {
            get {
                return ResourceManager.GetString("IntervalsArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИВР.
        /// </summary>
        internal static string IVR {
            get {
                return ResourceManager.GetString("IVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LF.
        /// </summary>
        internal static string LF {
            get {
                return ResourceManager.GetString("LF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В исходных данных не обнаружены необходимые физиологические сигналы..
        /// </summary>
        internal static string NoSignalInSourceData {
            get {
                return ResourceManager.GetString("NoSignalInSourceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показатель активности процессов регуляции (ПАПР).
        /// </summary>
        internal static string PAPR {
            get {
                return ResourceManager.GetString("PAPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pNN50.
        /// </summary>
        internal static string pNN50 {
            get {
                return ResourceManager.GetString("pNN50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Психофизиологическая цена адаптации (ПЦА).
        /// </summary>
        internal static string PPPA {
            get {
                return ResourceManager.GetString("PPPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отметки пульса.
        /// </summary>
        internal static string PulseMarks {
            get {
                return ResourceManager.GetString("PulseMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отметки пульса с оценкой достоверности.
        /// </summary>
        internal static string PulseMarksWithReliabilityEstimation {
            get {
                return ResourceManager.GetString("PulseMarksWithReliabilityEstimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMSSD.
        /// </summary>
        internal static string RMSSD {
            get {
                return ResourceManager.GetString("RMSSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S0.
        /// </summary>
        internal static string S0 {
            get {
                return ResourceManager.GetString("S0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры скатерограммы.
        /// </summary>
        internal static string ScatterParams {
            get {
                return ResourceManager.GetString("ScatterParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Альфа, мс.
        /// </summary>
        internal static string ScatterParams_Alpha {
            get {
                return ResourceManager.GetString("ScatterParams_Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Альфа / Бета.
        /// </summary>
        internal static string ScatterParams_AlphaByBeta {
            get {
                return ResourceManager.GetString("ScatterParams_AlphaByBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бета, мс.
        /// </summary>
        internal static string ScatterParams_Beta {
            get {
                return ResourceManager.GetString("ScatterParams_Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dN-N, мс.
        /// </summary>
        internal static string ScatterParams_dNN {
            get {
                return ResourceManager.GetString("ScatterParams_dNN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Индекс функционального состояния (ИФС), усл.ед..
        /// </summary>
        internal static string ScatterParams_FSI {
            get {
                return ResourceManager.GetString("ScatterParams_FSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sd.
        /// </summary>
        internal static string Sd {
            get {
                return ResourceManager.GetString("Sd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сигнал, полученный от устройства.
        /// </summary>
        internal static string SignalFromADC {
            get {
                return ResourceManager.GetString("SignalFromADC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось выделить фрагменты физиологических сигналов, соответствующие стимулам. Используется весь сигнал целиком..
        /// </summary>
        internal static string signals_fragments_not_aquired {
            get {
                return ResourceManager.GetString("signals_fragments_not_aquired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sm.
        /// </summary>
        internal static string Sm {
            get {
                return ResourceManager.GetString("Sm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В исходном сигнале обнаружено слишком мало сердечных сокращений!.
        /// </summary>
        internal static string too_few_heart_contractions_detected_in_signal {
            get {
                return ResourceManager.GetString("too_few_heart_contractions_detected_in_signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В исходном сигнале содержится слишком мало ({0}) NN-интервалов для расчета статистики..
        /// </summary>
        internal static string too_few_intervals_detected_in_signal {
            get {
                return ResourceManager.GetString("too_few_intervals_detected_in_signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В исходном сигнале содержится слишком мало ({0}) нормальных NN-интервалов для расчета статистики.
        ///Проверьте настройки отбраковки NN-интервалов!.
        /// </summary>
        internal static string too_few_valid_intervals_detected_in_signal {
            get {
                return ResourceManager.GetString("too_few_valid_intervals_detected_in_signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TP.
        /// </summary>
        internal static string TP {
            get {
                return ResourceManager.GetString("TP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to База заключений для матрицы состояний 5x5.
        /// </summary>
        internal static string TwoDimConclusionDatabase {
            get {
                return ResourceManager.GetString("TwoDimConclusionDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ULF.
        /// </summary>
        internal static string ULF {
            get {
                return ResourceManager.GetString("ULF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VLF.
        /// </summary>
        internal static string VLF {
            get {
                return ResourceManager.GetString("VLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВПР.
        /// </summary>
        internal static string VPR {
            get {
                return ResourceManager.GetString("VPR", resourceCulture);
            }
        }
    }
}
