//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PskOnline.Service.Test.Integration.UAT {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SampleTestDataJson {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleTestDataJson() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PskOnline.Service.Test.Integration.UAT.SampleTestDataJson", typeof(SampleTestDataJson).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;formatVersion&quot;:&quot;PskOnline-File-Based/0.1.0&quot;,
        ///    &quot;testData&quot;:{
        ///        &quot;PhSyncBegin&quot;:1,
        ///        &quot;PhSyncEnd&quot;:2,
        ///      &quot;TestInfo&quot;: {
        ///        &quot;Comment&quot;: &quot;&quot;,
        ///        &quot;Patient&quot;: {
        ///          &quot;Id&quot;: &quot;cf256785-d66d-4ab5-8dd2-362a2bbb805f&quot;,
        ///          &quot;Name&quot;: &quot;XXX&quot;,
        ///          &quot;Gender&quot;: 1,
        ///          &quot;BirthDate&quot;: &quot;1976-01-11T00:00:00&quot;,
        ///          &quot;BranchOfficeId&quot;: null,
        ///          &quot;BranchOfficeName&quot;: &quot;&quot;,
        ///          &quot;DepartmentId&quot;: null,
        ///          &quot;DepartmentName&quot;: &quot;&quot;,
        ///          &quot;PositionId&quot;: null,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sample_995_Hrv_Pass {
            get {
                return ResourceManager.GetString("Sample_995_Hrv_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;formatVersion&quot;:&quot;PskOnline-File-Based/0.1.0&quot;,
        ///    &quot;testData&quot;:{
        ///        &quot;Attempts&quot;:[{&quot;DelaySeconds&quot;:2.2997346614951897,&quot;IsTraining&quot;:true,&quot;Key&quot;:798,&quot;StimulusOccurredTime&quot;:&quot;0001-01-01T00:00:00+00:00&quot;,&quot;ReactionAcceptedTime&quot;:&quot;0001-01-01T00:00:00+00:00&quot;,&quot;ReactionTimeSeconds&quot;:0.226,&quot;ReactionError&quot;:0,&quot;PhSyncBegin&quot;:0,&quot;PhSyncEnd&quot;:0},{&quot;DelaySeconds&quot;:2.7424790089682114,&quot;IsTraining&quot;:true,&quot;Key&quot;:798,&quot;StimulusOccurredTime&quot;:&quot;0001-01-01T00:00:00+00:00&quot;,&quot;ReactionAcceptedTime&quot;:&quot;0001-01-01T00:00:00+00:00&quot;,&quot;ReactionTime [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sample_995_Svmr_ {
            get {
                return ResourceManager.GetString("Sample_995_Svmr_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;formatVersion&quot;: &quot;PskOnline-File-Based/0.1.0&quot;,
        ///  &quot;testData&quot;: {
        ///    &quot;PhSyncBegin&quot;: 1,
        ///    &quot;PhSyncEnd&quot;: 2,
        ///    &quot;TestInfo&quot;: {
        ///      &quot;Comment&quot;: &quot;&quot;,
        ///      &quot;Patient&quot;: {
        ///        &quot;Id&quot;: &quot;28285cc1-f21b-4f21-a03f-9ee5f71d9583&quot;,
        ///        &quot;Name&quot;: &quot;XXX&quot;,
        ///        &quot;Gender&quot;: 1,
        ///        &quot;BirthDate&quot;: &quot;1971-03-02T00:00:00&quot;,
        ///        &quot;BranchOfficeId&quot;: null,
        ///        &quot;BranchOfficeName&quot;: &quot;&quot;,
        ///        &quot;DepartmentId&quot;: null,
        ///        &quot;DepartmentName&quot;: &quot;&quot;,
        ///        &quot;PositionId&quot;: null,
        ///        &quot;PositionName&quot;: &quot;Начальник [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sample_999_Hrv_ConditionalPass {
            get {
                return ResourceManager.GetString("Sample_999_Hrv_ConditionalPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;formatVersion&quot;: &quot;PskOnline-File-Based/0.1.0&quot;,
        ///  &quot;testData&quot;: {
        ///    &quot;Attempts&quot;: [
        ///      {
        ///        &quot;DelaySeconds&quot;: 2.0737913912505803,
        ///        &quot;IsTraining&quot;: true,
        ///        &quot;Key&quot;: 798,
        ///        &quot;StimulusOccurredTime&quot;: &quot;0001-01-01T00:00:00+00:00&quot;,
        ///        &quot;ReactionAcceptedTime&quot;: &quot;0001-01-01T00:00:00+00:00&quot;,
        ///        &quot;ReactionTimeSeconds&quot;: 0.304,
        ///        &quot;ReactionError&quot;: 0,
        ///        &quot;PhSyncBegin&quot;: 0,
        ///        &quot;PhSyncEnd&quot;: 0
        ///      },
        ///      {
        ///        &quot;DelaySeconds&quot;: 2.943589387900936,
        ///        &quot;IsTr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sample_999_Svmr_ {
            get {
                return ResourceManager.GetString("Sample_999_Svmr_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;formatVersion&quot;: &quot;PskOnline-File-Based/0.1.0&quot;,
        ///  &quot;testData&quot;: {
        ///    &quot;PhSyncBegin&quot;: -1,
        ///    &quot;PhSyncEnd&quot;: -1,
        ///    &quot;TestInfo&quot;: {
        ///      &quot;Comment&quot;: null,
        ///        &quot;Patient&quot;: {
        ///          &quot;Id&quot;: &quot;cf256785-d66d-4ab5-8dd2-362a2bbb805f&quot;,
        ///          &quot;Name&quot;: &quot;XXX&quot;,
        ///          &quot;Gender&quot;: 1,
        ///          &quot;BirthDate&quot;: &quot;1976-01-11T00:00:00+00:00&quot;,
        ///          &quot;BranchOfficeId&quot;: null,
        ///          &quot;BranchOfficeName&quot;: &quot;&quot;,
        ///          &quot;DepartmentId&quot;: null,
        ///          &quot;DepartmentName&quot;: &quot;&quot;,
        ///          &quot;PositionId&quot;: null,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sample_Hrv_Intervals {
            get {
                return ResourceManager.GetString("Sample_Hrv_Intervals", resourceCulture);
            }
        }
    }
}
