//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PskOnline.Methods.Hrv.Processing.Logic.Pro {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class two_dim_conclusions_pro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal two_dim_conclusions_pro() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PskOnline.Methods.Hrv.Processing.Logic.Pro.two_dim_conclusions_pro", typeof(two_dim_conclusions_pro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена адаптации высокая. Низкий уровень функциональных возможностей регуляторных механизмов сердечно-сосудистой системы. Высокие уровни напряжения и утомления. Выраженное преобладание симпатического отдела вегетативной нервной системы. Максимальное напряжение в развитии стресса. Максимальный уровень эрготропной регуляции. Максимальное напряжение вегетативных механизмов сердечно-сосудистой системы. Частый стабильный пульс. Состояние максимального напряжения регуляторных функций. Резкая активация центрального  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conclusion_prof_1_1 {
            get {
                return ResourceManager.GetString("Conclusion_prof_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена адаптации высокая. Низкий уровень функциональных возможностей регуляторных механизмов сердечно-сосудистой системы. Уровни напряжения  и утомления выше среднего. Выраженная стадия сопротивления в развитии стресса. Выраженная эрготропная регуляция. Частый умеренно стабильный пульс.. Активизация центрального коркового контура регуляции сердечного ритма. Активация адренэргических механизмов. Повышение активности подкорковых нервных центров. Активация эрготропной системы со стабилизацией ритма. Выраженные к [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conclusion_prof_1_2 {
            get {
                return ResourceManager.GetString("Conclusion_prof_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена адаптации высокая. Низкий уровень функциональных возможностей регуляторных механизмов сердечно-сосудистой системы. Нарушение устойчивости к действию физических стрессоров. Напряжение оптимальное. Эрготропная регуляция. Частый пульс. Резкое преобладание центрального контура регуляции. Стадия напряжения физиологических систем в развитии стресса. Повышенный  уровень поведенческой и психической активности. Физическая работоспособность снижена. Повышение мышечного тонуса. Активация катоболитических процессо [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conclusion_prof_1_3 {
            get {
                return ResourceManager.GetString("Conclusion_prof_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена адаптации высокая. Низкий уровень функциональных возможностей регуляторных механизмов сердечно-сосудистой системы. Напряжение ниже среднего, появление выраженных явлений истощения в развития стресса. Умеренная активация трофотропной регуляции. Частый умеренно нестабильный пульс.  Низкий уровень работоспособности. Превышение уровня внешних и внутренних требований над функциональными возможностями организма. Проявления анаболитических процессов..
        /// </summary>
        internal static string Conclusion_prof_1_4 {
            get {
                return ResourceManager.GetString("Conclusion_prof_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена адаптации высокая. Низкий уровень функциональных возможностей регуляторных механизмов сердечно-сосудистой системы. Напряжение низкое, стадия  максимального истощения в развитии стресса.
        ///Частый нестабильный пульс. Дизрегуляция гуморальных и нервных влияний со снижением чувствительности симпатического отдела вегетативной нервной системы. Низкий уровень регуляторных возможностей сердечно-сосудистой системы. Резкая активизация центрального коркового контура регуляции на фоне явлений дестабилизации сердечн [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conclusion_prof_1_5 {
            get {
                return ResourceManager.GetString("Conclusion_prof_1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена адаптации неудовлетворительная. Ниже среднего уровень функциональных возможностей регуляторных механизмов сердечно-сосудистой системы. Высокие уровни напряжения и утомления. Выраженные явления сопротивления в развитии стресса.  Выраженная эрготропная регуляция. Учащенный пульс. Активизация центрального коркового контура регуляции сердечного ритма. Активация адренэргических механизмов. Повышение активности подкорковых нервных центров. Активация эрготропной системы со стабилизацией ритма. Выраженные ката [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conclusion_prof_2_1 {
            get {
                return ResourceManager.GetString("Conclusion_prof_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена адаптации неудовлетворительная. Ниже среднего уровень функциональных возможностей регуляторных  механизмов сердечно-сосудистой системы. Уровни напряжения  и утомления выше среднего. Преобладание симпатического отдела вегетативной нервной системы. Явления сопротивления в развитии стресса.Учащенный умеренно стабильный пульс. Выраженный уровень поведенческой активности и состояния адаптации к изменяющейся среде. Повышение мышечного тонуса. Активация катоболитических процессов. Повышенное состояние моторно [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conclusion_prof_2_2 {
            get {
                return ResourceManager.GetString("Conclusion_prof_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена адаптации неудовлетворительная. Ниже среднего уровень функциональных возможностей регуляторных механизмов сердечно-сосудистой системы. Напряжение оптимальное, утомление отсутствует. Пульс несколько чаще средних значений, с оптимальным напряжением регуляторных механизмов. Начальные проявления катоболитических процессов..
        /// </summary>
        internal static string Conclusion_prof_2_3 {
            get {
                return ResourceManager.GetString("Conclusion_prof_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена адаптации неудовлетворительная. Ниже среднего уровень функциональных возможностей регуляторных механизмов сердечно-сосудистой системы. Напряжение ниже среднего, появление явлений истощения в развитии стресса. Нарастание процессов трофотропной регуляции. Учащенный умеренно нестабильный пульс. Умеренная активизация центрального коркового контура регуляции сердечного ритма. Превышение уровня внешних и внутренних требований над функциональными возможностями организма..
        /// </summary>
        internal static string Conclusion_prof_2_4 {
            get {
                return ResourceManager.GetString("Conclusion_prof_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена адаптации неудовлетворительная. Ниже среднего уровень функциональных возможностей регуляторных механизмов сердечно-сосудистой системы. Напряжение низкое, появление выраженных явлений истощения в развитии стресса.
        ///Активация трофотропной регуляции. Учащенный нестабильный пульс.  Мобилизация ваго-инсулярного аппарата. Преобладание анаболических процессов, нутритивных функций процессов восстановления. Активизация систем поддержания гомеостатического равновесия. Сниженный уровень работоспособности..
        /// </summary>
        internal static string Conclusion_prof_2_5 {
            get {
                return ResourceManager.GetString("Conclusion_prof_2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена адаптации удовлетворительная. Средний уровень функциональных возможностей регуляторных механизмов сердечно-сосудистой системы. Высокое уровни напряжения и утомления. Явления сопротивления в развитии стресса. Эрготропная регуляция. Оптимальный уровень поведенческой активности и состояния адаптации к изменяющейся среде. Повышение мышечного тонуса. Активация катоболитических процессов. Хорошее состояние моторной готовности и вегетативной мобилизации. Готовность к борьбе. Обострение внимания..
        /// </summary>
        internal static string Conclusion_prof_3_1 {
            get {
                return ResourceManager.GetString("Conclusion_prof_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена адаптации удовлетворительная. Средний уровень функциональных возможностей регуляторных механизмов сердечно-сосудистой системы. Уровни напряжения  и утомления выше среднего. Умеренная активация эрготропной регуляции. Частота пульса оптимальная с высоким напряжением регуляторных механизмов. Явления стабилизации сердечного ритма с умеренным повышением психической и поведенческой активности, моторной готовности и вегетативной мобилизации. Эффективные механизмы регуляции сердечной деятельности. Начальные пр [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conclusion_prof_3_2 {
            get {
                return ResourceManager.GetString("Conclusion_prof_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена адаптации удовлетворительная. Средний уровень функциональных возможностей регуляторных механизмов сердечно-сосудистой системы Напряжение оптимальное, утомление отсутствует.
        ///Взаимоуравновешенность симпатического и парасимпатического отдела вегетативной  нервной системы. Взаимоуравновешенность  эрготропных и трофотропных процессов. Оптимальное функциональное состояние сердечно-сосудистой системы. Эффективные механизмы регуляции сердечной деятельности. Оптимальное сочетание автономного и центрального кон [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conclusion_prof_3_3 {
            get {
                return ResourceManager.GetString("Conclusion_prof_3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена адаптации удовлетворительная. Средний уровень функциональных возможностей регуляторных механизмов сердечно-сосудистой системы. Умеренная активация трофотропной регуляции. Эффективные механизмы регуляции сердечной деятельности.  Мобилизация ваго-инсулярного аппарата. Нарастание процессов восстановления жизненных сил. Напряжение ниже среднего, появление явлений истощения..
        /// </summary>
        internal static string Conclusion_prof_3_4 {
            get {
                return ResourceManager.GetString("Conclusion_prof_3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена адаптации удовлетворительная. Средний уровень функциональных возможностей регуляторных механизмов сердечно-сосудистой системы. Трофотропная регуляция. Напряжение низкое, явление истощения регуляторных возможностей. Мобилизация ваго-инсулярного аппарата. Преобладание процессов покоя, поддержание гомеостаза, психической релаксации, снижения мышечного тонуса..
        /// </summary>
        internal static string Conclusion_prof_3_5 {
            get {
                return ResourceManager.GetString("Conclusion_prof_3_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена адаптации низкая. Выше среднего уровень функциональных возможностей регуляторных механизмов сердечно-сосудистой системы. Высокие уровни напряжения и утомления. Нарастание явлений тревоги в развития стресса. Пульс реже оптимального с высоким напряжением регуляторных механизмов. Явления стабилизации сердечного ритма с умеренным повышением психической и поведенческой активности, моторной готовности и вегетативной мобилизации. Эффективные механизмы регуляции сердечной деятельности. Начальные проявления кат [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conclusion_prof_4_1 {
            get {
                return ResourceManager.GetString("Conclusion_prof_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена адаптации низкая. Выше среднего уровень функциональных возможностей регуляторных механизмов сердечно-сосудистой системы. Уровни напряжения  и утомления выше среднего. Уровни напряжения  и утомления выше среднего. Появление явлений тревоги в развития стресса. Пульс реже оптимального, напряжение регуляторных механизмов выше среднего..
        /// </summary>
        internal static string Conclusion_prof_4_2 {
            get {
                return ResourceManager.GetString("Conclusion_prof_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена адаптации низкая. Выше среднего уровень функциональных возможностей регуляторных механизмов сердечно-сосудистой системы. Напряжение оптимальное, утомление отсутствует. Пульс несколько реже средних значений, с оптимальным напряжением регуляторных механизмов..
        /// </summary>
        internal static string Conclusion_prof_4_3 {
            get {
                return ResourceManager.GetString("Conclusion_prof_4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена адаптации низкая. Выше среднего уровень функциональных возможностей регуляторных механизмов сердечно-сосудистой системы. Напряжение ниже среднего, появление явлений устойчивости к действию физических стрессоров. Трофотропная регуляция. Пульс реже оптимального, умеренно нестабильный. Мобилизация вагоинсулярного аппарата. Преобладание процессов покоя, поддержание гомеостаза, психической релаксации, снижения мышечного тонуса. Выраженное торможение моторной соматической системы..
        /// </summary>
        internal static string Conclusion_prof_4_4 {
            get {
                return ResourceManager.GetString("Conclusion_prof_4_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена адаптации низкая. Выше среднего уровень функциональных возможностей регуляторных механизмов сердечно-сосудистой системы. Напряжение низкое, выраженные явления  устойчивости к действию физических стрессоров. Выраженная  активация трофотропной регуляции. Пульс реже оптимального, нестабильный. Невысокий уровень напряжения функционирования регуляторных систем. Сниженный уровень артериального давления. Выраженные анаболитические процессы. Активизация систем поддержания гомеостатического равновесия..
        /// </summary>
        internal static string Conclusion_prof_4_5 {
            get {
                return ResourceManager.GetString("Conclusion_prof_4_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена адаптации очень низкая. Высокий уровень функциональных возможностей регуляторных механизмов сердечно-сосудистой системы. Высокое реактивное напряжение и  состояние утомления. Дизрегуляция эрготропных и трофотропных механизмов регуляции. Стадия максимальной выраженности аларм - реакции в развитие стресса. Редкий стабильный пульс. Дисрегуляторный синдром..
        /// </summary>
        internal static string Conclusion_prof_5_1 {
            get {
                return ResourceManager.GetString("Conclusion_prof_5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена адаптации очень низкая. Высокий уровень функциональных возможностей регуляторных механизмов сердечно-сосудистой системы. Нарастание явлений тревоги в развития стресса. Выше среднего реактивное напряжение и  состояние утомления. Редкий умеренно стабильный пульс..
        /// </summary>
        internal static string Conclusion_prof_5_2 {
            get {
                return ResourceManager.GetString("Conclusion_prof_5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена адаптации очень низкая. Высокий уровень функциональных возможностей регуляторных механизмов сердечно-сосудистой системы. Напряжение оптимальное, утомление отсутствует. Устойчивость к действию физических стрессоров. Редкий пульс с оптимальным напряжением регуляторных механизмов. Преобладание процессов покоя, поддержание гомеостаза, психической релаксации, снижения мышечного тонуса..
        /// </summary>
        internal static string Conclusion_prof_5_3 {
            get {
                return ResourceManager.GetString("Conclusion_prof_5_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена адаптации очень низкая. Высокий уровень функциональных возможностей регуляторных механизмов сердечно-сосудистой системы. Напряжение ниже среднего, выраженные явления  устойчивости к действию физических стрессоров. Мобилизация ваго-инсулярного аппарата. Выраженная активация трофотропной регуляции. Редкий умеренно нестабильный пульс. Невысокий уровень напряжения функционирования регуляторных систем. Сниженный уровень артериального давления. Состояние покоя. Выраженные анаболитические процессы..
        /// </summary>
        internal static string Conclusion_prof_5_4 {
            get {
                return ResourceManager.GetString("Conclusion_prof_5_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена адаптации очень низкая. Высокий уровень функциональных возможностей регуляторных механизмов сердечно-сосудистой системы. Низкий уровень напряжения функционирования регуляторных систем. Выраженное преобладание парасимпатического отдела вегетативной нервной системы. Редкий нестабильный пульс. Выраженная активация трофотропной системы, вагоинсулярного аппарата. Преобладание анаболических процессов. Выраженное мышечное расслабление, которое связано либо сонливостью, либо с утомлением. Угроза вагоинсулярног [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conclusion_prof_5_5 {
            get {
                return ResourceManager.GetString("Conclusion_prof_5_5", resourceCulture);
            }
        }
    }
}
